leftnav:
- identifier: bfeb8f7b-208f-beb5-0e7f-4f9e483283f8
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: e1fc585f-0b82-4576-cc79-7912db5d07cb
  name: Readings
  url: /pages/readings
  weight: 20
- identifier: 586cd00f-2ba6-f0db-ce37-f83a3a2e4507
  name: Assignments
  url: /pages/assignments/
  weight: 30
- identifier: 5ee9675b-d819-e94f-5f72-5dfbc79dc451
  name: Paper 1
  parent: 586cd00f-2ba6-f0db-ce37-f83a3a2e4507
  url: /pages/assignments/paper-1
  weight: 40
- identifier: 8b245b2f-e2ab-9848-35ab-7f9016d966e5
  name: Paper 2
  parent: 586cd00f-2ba6-f0db-ce37-f83a3a2e4507
  url: /pages/assignments/paper-2
  weight: 50
- identifier: 05416e54-4c39-df41-4a15-905d1aaec331
  name: Final Paper
  parent: 586cd00f-2ba6-f0db-ce37-f83a3a2e4507
  url: /pages/assignments/final-paper
  weight: 60
- identifier: e25d3882-7cb6-410c-0a73-1a5b1598a128
  name: 'Related Resources '
  url: /pages/related-resources
  weight: 70
